### ISSUE TITLE
Diferencia entre DTO y Model

### ISSUE THREAD

**Issue by Gianotti** [fgallo94/StrategyPatternTP1#5]
Fede fijate que todo lo que tenes en dto en realidad seria model, un dto es para cuando necesitas ocultar info o una entidad de logica, si fuera un servicio rest para dar de alta un vikingo o espartano, tendrias un dto con toda la informacion de ambos, haceme acordar en clase y lo explico mejor.
https://stackoverflow.com/questions/1612334/difference-between-dto-vo-pojo-javabeans

**Comment by fgallo94** [comment]
Gracias por la información fe de erratas lo ocurrido. Solucionado en el ultimo commit de la rama master.
